language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
    - $TESTCMD -e 'using Pkg;
          Pkg.add(PackageSpec(url="https://github.com/jonathanBieler/GtkExtensions.jl.git", rev="master"));
          Pkg.add(PackageSpec(url="https://github.com/jonathanBieler/RemoteGtkREPL.jl.git", rev="master"));
          Pkg.add(PackageSpec(url="https://github.com/jonathanBieler/JuliaWordsUtils.jl.git", rev="master"));
          Pkg.add(PackageSpec(url="https://github.com/jonathanBieler/GtkTextUtils.jl.git", rev="master"));
          Pkg.clone(pwd());
          Pkg.build("GtkREPL");
          Pkg.test("GtkREPL"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("GtkREPL"));
                Pkg.add("Coverage");
                using Coverage;
                Coveralls.submit(Coveralls.process_folder())'